name: 'GitHub Release Notes JSON Generator'
description: 'A small little GitHub action that converts release notes of github releases into a json format'
inputs:
  version:
    description: 'Which version should we delete the assets from?'
    required: false
    default: ''
  destination:
    description: 'Where should the resulting release notes be saved to (i.e. `./config/release-notes.json`)'
    required: true
    default: ''
  github-access-token:
    description: 'The GitHub access token required to delete the assets & discover non released versions'
    required: true
    default: ''
runs:
  using: 'node12'
  main: 'index.js'
